language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: secret-reef-88384
  api_key:
    secure: EkZikc61KgZyoF9CTw1fdd803KfohnczTioQXpKCr0zBg/CNcTZiTZTrM1bVOPrJ6R+9YOCcKAJDu5uhsaJq9AEP9T38EuqC9d1YCDcu1EoIlFk1ECotFYPnKwj7fpLG7t2OIQxmc9pFUmNQ18JNkbR/NpueP0nG/FLStDXQBNTMPIM5rV0hOYT7JGM7FQBUbZsXZ5ikDLSAiq0L+RZ5UmXSfqxB/S3mRcK2tzkPtzu9QhH0p9pb8wRW/qLX4VikFQqnrv512akFmoyIop5h7fpMy71ANwynhh4ARe+aRS2BD8m/lymZVS8R2lfZTu33EGG1cNErcbMe57jk71ECEHvJYMlpFrNjLtmw8MejEU+Z/tii60AZl3+vejS72cw1s1VQPR93QrARXEvXluSfwc4LdM50PmjMHQY/RVdWrq0a7b0RPd9F8aYKvgIb7CEHsnLZZDuBHqFY9KGFVw7PCuDovFNKtKGdCkmjkSnDPYg6XAbdIzfCYlbsNjRSv+e0kX4rv76jmNiwlY5Hf9E6Oj59XacUa0Xlwxl2oCmUUhV1wfWDsGOWXKNPEjuYlUFe6M3gcabvYAkvXKJcyHwmajBWVCk+ySu9HFO1L2KgpiVYvKSbOZOe5DQ2pZsleiDXpHwBq/j3PQZAU9XyB1Ngtme/cg7zVX5CFIGIuTeGmMM=
